### ISSUE TITLE
Create a module for auditing GSA usage via IAM audit logs

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/terraform-infra-common#148]
ref: https://github.com/chainguard-dev/terraform-infra-common/pull/139

With this we should be able to check things like:

```[tasklist]
### Tasks
- [ ] Pub/Sub usage for event delivery
- [ ] BigQuery DTS usage for ingestion
- [ ] Workload identity usage for things like GitHub Actions WIF
- [ ] Flag private key creation events
```
